CREATE TABLE IF NOT EXISTS Jogador (
    id_jogador INT GENERATED ALWAYS AS IDENTITY,
    progresso VARCHAR(50) NOT NULL,
    vida INT,
    poder VARCHAR(50),
    PRIMARY KEY(id_jogador)
);

CREATE TABLE IF NOT EXISTS chooselife (
    chooselife_id INT GENERATED ALWAYS AS IDENTITY,
    test_id INT,
    seila VARCHAR(50),
    arroz INT,
    telefone VARCHAR(50),
    PRIMARY KEY(chooselife_id),
    CONSTRAINT fk_test
      FOREIGN KEY(test_id) 
	    REFERENCES test(test_id)
);

CREATE TABLE IF NOT EXISTS Item ();
CREATE TABLE IF NOT EXISTS Inventario ();
CREATE TABLE IF NOT EXISTS Bau ();
CREATE TABLE IF NOT EXISTS Nivel ();
CREATE TABLE IF NOT EXISTS Sala();
CREATE TABLE IF NOT EXISTS NPC();
CREATE TABLE IF NOT EXISTS Boss ();
CREATE TABLE IF NOT EXISTS Inimigo ();
CREATE TABLE IF NOT EXISTS Comum ();
CREATE TABLE IF NOT EXISTS Amigavel ();
CREATE TABLE IF NOT EXISTS Narrador ();
CREATE TABLE IF NOT EXISTS Amigo ();
CREATE TABLE IF NOT EXISTS Arma ();
CREATE TABLE IF NOT EXISTS Magico ();
CREATE TABLE IF NOT EXISTS Codigo ();
